apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  namespace: argo
spec:
  containers:
    - name: busybox
      image: busybox:1.28
      args:
        - sleep
        - "1000000"
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-ecr-secret
              key: AWS_ACCESS_KEY_ID.txt
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-ecr-secret
              key: AWS_SECRET_ACCESS_KEY.txt
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-ecr-secret
              key: AWS_DEFAULT_REGION.txt
  restartPolicy: Never
