apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
  namespace: argo
spec:
  containers:
    - name: busybox-container
      image: amazon/aws-cli
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-ecr-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-ecr-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-ecr-secret
              key: AWS_DEFAULT_REGION
  restartPolicy: Never
